on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - run: ./build.ps1 -t build -c Release
        shell: pwsh
      - run: ./build.ps1 -t pack -c Release --no-build
        shell: pwsh
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            artifacts/pkg/*.nupkg
            artifacts/pkg/*.snupkg
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - run: ./build.ps1 -t test
        shell: pwsh
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: artifacts/pkg
      - run: ./build.ps1 -t artifacts/push/nuget
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    needs: [build, test]
